version: "3"
services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
      - POSTGRESQL_EXTRA_DATABASES=backend_db
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    ports:
      - "5432:5432"

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
    depends_on:
      - postgresql
    volumes:
      - "./keycloak_themes:/opt/bitnami/keycloak/themes/mynewtheme"
      - "./keycloak_import_realm:/opt/bitnami/keycloak/data/import"
      - "./keycloak_exported_realm:/export"
volumes:
  postgresql_data:
    driver: local
